### ISSUE TITLE
Trying to download clip downloads live stream instead and clip doesn't work

### ISSUE THREAD

**Issue by superbonaci** [DmitryScaletta/twitch-dlp#11]
Trying to download a clip, but what happens is the stream is live so downloads it instead:

```
$ npx twitch-dlp 'https://www.twitch.tv/chess/clip/ConcernedGiantWolfHassanChop-P98N40l3ZaIBY-Vl?filter=clips&range=7d&sort=time'
Downloading stream metadata
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/chess
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Writing output to
/home/memetix_/twitch-dlp/chess (live) 2024-08-12 15_07 [42926217177].mp4
[plugins.twitch][info] Will skip ad segments
```

If the stream is not live fails to download clip:

```
$ npx twitch-dlp 'https://www.twitch.tv/memetix_/clip/WimpyBlatantCaterpillarRickroll-iXd1K1hskFq2lskS?filter=clips&range=all&sort=time'
Downloading stream metadata
/home/memetix_/twitch-dlp/twitch-dlp.js:719
      throw new Error('The channel is not currently live');
            ^

Error: The channel is not currently live
    at main (/home/memetix_/twitch-dlp/twitch-dlp.js:719:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v22.6.0
```

**Comment by superbonaci** [comment]
Clips are always public right? No sub-only clips?

**Comment by DmitryScaletta** [comment]
twitch-dlp currently doesn't support downloading clips.

> Clips are always public right? No sub-only clips?

Yes.

**Comment by superbonaci** [comment]
Another clip that is not working:
https://www.twitch.tv/fauxre/clip/AmusedRichGnatBudStar-nPqtbh0kewe0wFAH?filter=clips&range=7d&sort=time

**Comment by DmitryScaletta** [comment]
> Another clip that is not working

Currently I don't have plans adding support for clips.
You can use `yt-dlp` for that.

**Comment by superbonaci** [comment]
> > Another clip that is not working
> 
> Currently I don't have plans adding support for clips. You can use `yt-dlp` for that.

Thanks. Since they are public makes sense do not duplicate efforts many other apps can do it.
