### ISSUE TITLE
Private/hidden VODs retrieval console javascript - returns error

### ISSUE THREAD

**Issue by testdev123456** [DmitryScaletta/twitch-dlp#13]
I followed the tutorial from:
https://github.com/DmitryScaletta/twitch-dlp/blob/master/DOWNLOAD_PRIVATE_VIDEOS.md

For example, on https://streamscharts.com/channels/username/streams/123456 
The javascript code that we should enter in Console to grab the VOD data returns this error:

```
Uncaught TypeError: Cannot read properties of null (reading 'dataset')
    at <anonymous>:7:81
```

Tried with public or private recent streams without luck

**Comment by DmitryScaletta** [comment]
Thanks for the report.
I just updated the script, it should work now.

**Comment by testdev123456** [comment]
it works! Thanks!!
