### ISSUE TITLE
Fragments are deleted even if merging fails

### ISSUE THREAD

**Issue by techno156** [DmitryScaletta/twitch-dlp#15]
Once FFMPEG terminates, the files are deleted, even if the process failed to merge the files. 

This is not ideal if the merge fails, such as if there is insufficient space for the drive, as the user would then have to re-download the stream again, which may not be possible if the streamer is no longer live, and the VOD is not available.

Instead, the files should be preserved if the merge process fails, with the incomplete merge optionally deleted.

**Comment by DmitryScaletta** [comment]
Good idea. Thanks for the suggestion.

For now you can use `--keep-fragments` flag and manually delete all fragments after merging.

**Comment by superbonaci** [comment]
Maybe another option `--keep-fragments-failure` so fragments are kept only when fails.

**Comment by DmitryScaletta** [comment]
> the files should be preserved if the merge process fails

Done in v0.3.1

**Comment by superbonaci** [comment]
Thanks!
