### ISSUE TITLE
Only half of the VOD was downloaded (Sub only) 

### ISSUE THREAD

**Issue by Me-Arash** [DmitryScaletta/twitch-dlp#18]
I downloaded a VOD using the sub only method. The problem is that out of 04:36:39, only the first 02:55:24 was downloaded.

Q_ what is the problem and how to fix it in future.

Q_ how to download the rest of the vod.

**Comment by DmitryScaletta** [comment]
It's hard to tell without a link.
Can you please provide the VOD link on twitchtracker or streamscharts (whichever you use)?

**Comment by DmitryScaletta** [comment]
If you have a problem with downloading or merging fragments, it's impossible to investigate the issue without a link to that video (you can send me the link via discord if you want, my nickname is the same as here).

If you asking how to download specific part of the video, you can use `--download-sections` argument like this:

```bash
npm dlx twitch-dlp LINK --download-sections "*2:55:24-inf"
```

Where `inf` means the end of the video.
