### ISSUE TITLE
Some videos can't be downloaded

### ISSUE THREAD

**Issue by superbonaci** [DmitryScaletta/twitch-dlp#20]
All the videos can be downloaded except one:
This video is only available to subscribers. Sub now to watch and support FAUXRE.

```
$ npx twitch-dlp -F 'https://www.twitch.tv/videos/2314836332'
Downloading video access token
Downloading video metadata
Downloading video manifest
Trying to get playlist url from video metadata
Trying to get playlist url from video metadata. Method 2
This video might be hidden or sub-only. Follow this article to download it: https://github.com/DmitryScaletta/twitch-dlp/blob/master/DOWNLOAD_PRIVATE_VIDEOS.md
```
```
$ npx twitch-dlp -F 'video:fauxre_52549941741_1732986014'
┌─────────┐
│ (index) │
├─────────┤
└─────────┘
```

[52549941741_chunked_url.txt](https://github.com/user-attachments/files/18271043/52549941741_chunked_url.txt)
[52549941741_index-dvr.m3u8.txt](https://github.com/user-attachments/files/18271049/52549941741_index-dvr.m3u8.txt)

The VOD will expire by the end of January so check it before that please.

Some twitch links fail but work the other way maybe this could be improved?:

```
$ npx twitch-dlp -F 'https://www.twitch.tv/videos/2338335989'
Downloading video access token
Downloading video metadata
Downloading video manifest
Trying to get playlist url from video metadata
Trying to get playlist url from video metadata. Method 2
This video might be hidden or sub-only. Follow this article to download it: https://github.com/DmitryScaletta/twitch-dlp/blob/master/DOWNLOAD_PRIVATE_VIDEOS.md

$ npx twitch-dlp -F 'video:fauxre_52802182973_1735419012'
┌─────────┬──────────────┐
│ (index) │ format_id    │
├─────────┼──────────────┤
│ 0       │ 'Source'     │
│ 1       │ '720p60'     │
│ 2       │ '480p30'     │
│ 3       │ '360p30'     │
│ 4       │ '160p30'     │
│ 5       │ 'Audio_Only' │
└─────────┴──────────────┘
```

**Comment by DmitryScaletta** [comment]
> ```https://www.twitch.tv/videos/2314836332```

Looks like both twitchtracker and streamcharts are storing wrong information for this stream.
It's just 1 second off, but it's enough to not working.

```ts
video:fauxre_52549941741_1732986014 // from twitchtracker and streamcharts
video:fauxre_52549941741_1732986013 // the real one
```

I don't think there's much I can do here.

If you have a subscription and you want to download sub only VOD, you can use `yt-dlp`

```bash
yt-dlp https://full_link_to_index-dvr.m3u8
```

> Some twitch links fail but work the other way maybe this could be improved?

It's not so easy. See [FAQ](https://github.com/DmitryScaletta/twitch-dlp/blob/master/DOWNLOAD_PRIVATE_VIDEOS.md#faq) for details.

**Comment by superbonaci** [comment]
There's more that can only be downloaded from tracker:

```
$ npx twitch-dlp -F 'https://www.twitch.tv/videos/2288876082'
Downloading video access token
Downloading video metadata
Downloading video manifest
Trying to get playlist url from video metadata
Trying to get playlist url from video metadata. Method 2
This video might be hidden or sub-only. Follow this article to download it: https://github.com/DmitryScaletta/twitch-dlp/blob/master/DOWNLOAD_PRIVATE_VIDEOS.md

$ npx twitch-dlp -F 'video:fauxre_52306003149_1730251613'
┌─────────┬──────────────┐
│ (index) │ format_id    │
├─────────┼──────────────┤
│ 0       │ 'Source'     │
│ 1       │ '720p60'     │
│ 2       │ '480p30'     │
│ 3       │ '360p30'     │
│ 4       │ '160p30'     │
│ 5       │ 'Audio_Only' │
└─────────┴──────────────┘
```

**Comment by superbonaci** [comment]
> > `https://www.twitch.tv/videos/2314836332`
> 
> Looks like both twitchtracker and streamcharts are storing wrong information for this stream. It's just 1 second off, but it's enough to not working.
> 
> ```ts
> video:fauxre_52549941741_1732986014 // from twitchtracker and streamcharts
> video:fauxre_52549941741_1732986013 // the real one
> ```
> 
> I don't think there's much I can do here.
> 
> If you have a subscription and you want to download sub only VOD, you can use `yt-dlp`
> 
> ```shell
> yt-dlp https://full_link_to_index-dvr.m3u8
> ```
> 
> > Some twitch links fail but work the other way maybe this could be improved?
> 
> It's not so easy. See [FAQ](https://github.com/DmitryScaletta/twitch-dlp/blob/master/DOWNLOAD_PRIVATE_VIDEOS.md#faq) for details.

Is is possible that the information was provided wrong by Twitch API?
Maybe the 1 second thing happens often. Could you improve the code to check for 1 second before and after too?

For example if twitchtracker and streamcharts report `video:fauxre_52549941741_1732986014` check these:

```
video:fauxre_52549941741_1732986013
video:fauxre_52549941741_1732986014
video:fauxre_52549941741_1732986015
```

check that if none is online throw the error or if more than one is only too, because that is weird. Do you think this is a good  approach?

**Comment by DmitryScaletta** [comment]
> Maybe the 1 second thing happens often due to some round to seconds stuff. Could you improve the code to check for 1 second before and after too?

I think it makes sense if it happens often. But for now we only have one case.

**Comment by superbonaci** [comment]
This is the info provided by the API:

```
$ curl -X GET 'https://api.twitch.tv/helix/videos?id=2314836332' -H 'Authorization: Bearer OAuth' -H 'Client-Id: ClientID'
{"data":[{"id":"2314836332","stream_id":"52549941741","user_id":"127650107","user_login":"fauxre","user_name":"FAUXRE","title":"hey!!!","description":"","created_at":"2024-11-30T17:00:20Z","published_at":"2024-11-30T17:00:20Z","url":"https://www.twitch.tv/videos/2314836332","thumbnail_url":"https://static-cdn.jtvnw.net/cf_vods/d2nvs31859zcd8/30e30379ef7d2d5a7513_fauxre_52549941741_1732986013/thumb/custom-bbb8a757-0057-4fb2-bbc4-d14827c6572a-%{width}x%{height}.jpeg","viewable":"public","view_count":4375,"language":"en","type":"archive","duration":"5h28m30s","muted_segments":null}],"pagination":{}}
```

**Comment by superbonaci** [comment]
> > Maybe the 1 second thing happens often due to some round to seconds stuff. Could you improve the code to check for 1 second before and after too?
> 
> I think it makes sense if it happens often. But for now we only have one case.

Yep I checked all other VOD and others channels too and there's only one case, but probably this is the only one found because few people is checking this stuff. If you would like to add the improvement that I suggest what would be great, also add a comment to it.

**Comment by DmitryScaletta** [comment]
> This is the info provided by the API:
> 
> ```
> {"data":[{"id":"2314836332","stream_id":"52549941741","user_id":"127650107","user_login":"fauxre","user_name":"FAUXRE","title":"hey!!!","description":"","created_at":"2024-11-30T17:00:20Z","published_at":"2024-11-30T17:00:20Z","url":"https://www.twitch.tv/videos/2314836332","thumbnail_url":"https://static-cdn.jtvnw.net/cf_vods/d2nvs31859zcd8/30e30379ef7d2d5a7513_fauxre_52549941741_1732986013/thumb/custom-bbb8a757-0057-4fb2-bbc4-d14827c6572a-%{width}x%{height}.jpeg","viewable":"public","view_count":4375,"language":"en","type":"archive","duration":"5h28m30s","muted_segments":null}],"pagination":{}}
> ```

I tested it before. It doesn't work. It always a few seconds off.
The API returns `2024-11-30T17:00:20Z` but it should be `2024-11-30 17:00:13`

**Comment by DmitryScaletta** [comment]
> ```https://www.twitch.tv/videos/2314836332```
> ```https://www.twitch.tv/videos/2338335989```

Should work fine now in v0.2.18

**Comment by superbonaci** [comment]
Yes, the 2 that are still online are working with at lease one of the methods:

video 1:

```
$ npx twitch-dlp -F 'https://www.twitch.tv/videos/2314836332'
Downloading video access token
Downloading video metadata
Downloading video manifest
Trying to get playlist url from video metadata
┌─────────┬──────────────┐
│ (index) │ format_id    │
├─────────┼──────────────┤
│ 0       │ 'Source'     │
│ 1       │ '720p60'     │
│ 2       │ '360p30'     │
│ 3       │ 'Audio_Only' │
└─────────┴──────────────┘

$ npx twitch-dlp -F 'video:fauxre_52549941741_1732986014'
┌─────────┐
│ (index) │
├─────────┤
└─────────┘
```

video 2:

```
$ npx twitch-dlp -F 'https://www.twitch.tv/videos/2338335989'
Downloading video access token
Downloading video metadata
Downloading video manifest
Trying to get playlist url from video metadata
┌─────────┬──────────────┐
│ (index) │ format_id    │
├─────────┼──────────────┤
│ 0       │ 'Source'     │
│ 1       │ '720p60'     │
│ 2       │ '480p30'     │
│ 3       │ '360p30'     │
│ 4       │ '160p30'     │
│ 5       │ 'Audio_Only' │
└─────────┴──────────────┘

$ npx twitch-dlp -F 'video:fauxre_52802182973_1735419012'
┌─────────┬──────────────┐
│ (index) │ format_id    │
├─────────┼──────────────┤
│ 0       │ 'Source'     │
│ 1       │ '720p60'     │
│ 2       │ '480p30'     │
│ 3       │ '360p30'     │
│ 4       │ '160p30'     │
│ 5       │ 'Audio_Only' │
└─────────┴──────────────┘
```

This one has already been deleted from Twitch so doesn't work:

```
$ npx twitch-dlp -F 'https://www.twitch.tv/videos/2288876082'
Downloading video access token
Downloading video metadata
This video might be hidden or sub-only. Follow this article to download it: https://github.com/DmitryScaletta/twitch-dlp/blob/master/DOWNLOAD_PRIVATE_VIDEOS.md

$ npx twitch-dlp -F 'video:fauxre_52306003149_1730251613'
┌─────────┐
│ (index) │
├─────────┤
└─────────┘
```

**Comment by superbonaci** [comment]
> > This is the info provided by the API:
> > ```
> > {"data":[{"id":"2314836332","stream_id":"52549941741","user_id":"127650107","user_login":"fauxre","user_name":"FAUXRE","title":"hey!!!","description":"","created_at":"2024-11-30T17:00:20Z","published_at":"2024-11-30T17:00:20Z","url":"https://www.twitch.tv/videos/2314836332","thumbnail_url":"https://static-cdn.jtvnw.net/cf_vods/d2nvs31859zcd8/30e30379ef7d2d5a7513_fauxre_52549941741_1732986013/thumb/custom-bbb8a757-0057-4fb2-bbc4-d14827c6572a-%{width}x%{height}.jpeg","viewable":"public","view_count":4375,"language":"en","type":"archive","duration":"5h28m30s","muted_segments":null}],"pagination":{}}
> > ```
> 
> I tested it before. It doesn't work. It always a few seconds off. The API returns `2024-11-30T17:00:20Z` but it should be `2024-11-30 17:00:13`

yes that's probably because they copy the stream from live to highlight and the creation dates vary slightly. The method I suggested to check a few seconds before and after could work if it's not difficult to implement.

**Comment by superbonaci** [comment]
I've realised that [2314836332](https://www.twitch.tv/videos/2314836332) is a past broadcast not highlight. Maybe the few seconds off has some explanation but IDK.

The metadata by TwitchDownloaderCLI uses the same date as the API `Created at: 2024-11-30 17:00:20Z`:

```
;FFMETADATA1
title=hey!!! (2314836332)
artist=FAUXRE
date=2024
genre=Just Chatting
comment=Created at: 2024-11-30 17:00:20Z\
Video id: 2314836332\
Views: 4375
[CHAPTER]
TIMEBASE=1/1000
START=0
END=19710000
title=Just Chatting
```
