### ISSUE TITLE
Can't download sub-only highlight (2)

### ISSUE THREAD

**Issue by superbonaci** [DmitryScaletta/twitch-dlp#21]
Subscription-only highlight:

```
$ npx twitch-dlp -F 'https://www.twitch.tv/videos/976147031'
Downloading video access token
Downloading video metadata
Downloading video manifest
Trying to get playlist url from video metadata
Trying to get playlist url from video metadata. Method 2
This video might be hidden or sub-only. Follow this article to download it: https://github.com/DmitryScaletta/twitch-dlp/blob/master/DOWNLOAD_PRIVATE_VIDEOS.md
```

I couldn't find anything in twitchtracker or streamcharts.

[976147031_chunked_url.txt](https://github.com/user-attachments/files/18271317/976147031_chunked_url.txt)
[976147031_index-dvr.m3u8.txt](https://github.com/user-attachments/files/18271318/976147031_index-dvr.m3u8.txt)

**Comment by DmitryScaletta** [comment]
> I couldn't find anything in twitchtracker or streamcharts.

They only store information about live broadcasts, not highlights.

> ```https://www.twitch.tv/videos/976147031```

Looks like this highlight is pretty old.
Twitch uses different method to generate playlist url.
The real video timestamp is `1617621854` but in the url it's `8716013363`.
Probably it's just random number.

It means we can't download some old sub only highlights.

**Comment by DmitryScaletta** [comment]
> ```https://www.twitch.tv/videos/976147031```

Should work fine now in v0.2.18
